services:
  db:
    image: postgres:17-alpine
    container_name: dns-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

#  redis:
#    image: redis:7
#    container_name: online_shop-redis
#    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
#    ports:
#      - "6381:6379"

  web:
    build: .
    container_name: dns-web
    env_file:
      .env
    depends_on:
      - db
#      - redis
    ports:
      - "5002:5000"
    command: ["waitress-serve", "--host=0.0.0.0", "--port=5000", "wsgi:application"]
    restart: unless-stopped

volumes:
  postgres_data: